### ISSUE TITLE
Invalid Database name

### ISSUE THREAD

**Issue by levi106** [Microsoft/intelligent-apps#84]
Project
AdatumTaxCorpKnowledgeData

File
Script.PostDeployment.sql

Branch
PBI1-Begin and PBI1-End

Description
```
USE [AdatumTaxCorpKnowledgeService20171127064957_db]
```
should be
```
USE [AdatumTaxCorpKnowledgeData]
```

**Comment by leo-leong** [comment]
this is now fixed.
