### ISSUE TITLE
Could not found file 'AdatumTaxCorpKnowledgeService\AdatumTaxCorpKnowledgeService\bin\roslyn\csc.exe'

### ISSUE THREAD

**Issue by levi106** [Microsoft/intelligent-apps#85]
## Version:
Visual Studio Enterprise 2017 15.9.11

## Repro Step:

1. Checkout PBI1-Begin branch
2. Build AdatumTaxCorpKnowledgeService project
3. Run

## Expected:

FAQ site will be shown.

## Actual:

I get the following error:
Could not find a part of the path 'XXX\AdatumTaxCorpKnowledgeService\AdatumTaxCorpKnowledgeService\bin\roslyn\csc.exe'

**Comment by levi106** [comment]
I found the following workaround:

1. Checkout PBI1-Begin branch
2. Build AdatumTaxCorpKnowledgeService project
3. Clean project
4. Build project again
5. Run

**Comment by leo-leong** [comment]
This is most likely caused by the .NET 4.7.1 Developer Pack not installed. Download https://dotnet.microsoft.com/download/thank-you/net471-developer-pack
